<?php

namespace AppBundle\Repository;

/**
 * ActivitesSportivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivitesSportivesRepository extends \Doctrine\ORM\EntityRepository
{
}
