<?php

namespace AppBundle\Repository;

/**
 * CausesSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CausesSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
