<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitiesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CitiesRepository extends EntityRepository
{

    public function findCityByTerm($term){
        $queryBuilder   = $this->createQueryBuilder('c')
            ->where('c.city LIKE :city')
            ->orWhere('c.countryName LIKE :country')
            ->orWhere('c.stateName LIKE :state')
            ->setParameters(['city' => '%'.$term.'%', 'country' => '%'.$term.'%', 'state' => '%'.$term.'%']);

        return $queryBuilder->getQuery()->getScalarResult();



    }
}
