<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountriesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CountriesRepository extends EntityRepository
{
   
    public function findCountryByTerm($term){
        $queryBuilder   = $this->createQueryBuilder('c')
            ->where('c.countryName LIKE :name')
            ->setParameter('name','%'.$term.'%');

        return $queryBuilder->getQuery()->getScalarResult();



    }
}
