<?php

namespace AppBundle\Repository;

/**
 * EtapeThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
