<?php

namespace AppBundle\Repository;

/**
 * EtapeEpingleeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeEpingleeRepository extends \Doctrine\ORM\EntityRepository
{
}
