<?php

namespace AppBundle\Repository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{


    public function searchVoyagesByAddress($request){
        $address        = @$request['address'];
        $locality       = @$request['locality'];
        $lat            = @$request['lat'];
        $lng            = @$request['lng'];
        $adminArea      = @$request['administrative_area_3'];
        $country        = @$request['country'];
        $ageMaxi        = @$request['ageMax'];
        $ageMini        = @$request['ageMin'];
        $dateSejour1    = @$request['dateFinSejour1'];
        $dateSejour2    = @$request['dateFinSejour2'];
        $smockerAllowed = @$request['smockerAllowed'];
        $genreVoyageurs = @$request['genreVoyageurs'];

        $parameters     = [];

        if($lat == '' || $lng== '') return null;

        $query  = $this->createQueryBuilder('e')
            ->join('e.lieuArrivee','lieuArrivee')
            ->join('e.lieuDepart','lieuDepart')
            ->join('e.voyage','voyage')
            ->select('lieuArrivee')
            ->select('lieuDepart')
            ->select('voyage')
            ->select(
                '(
                    ACOS(
                        SIN(:lat * PI() / 180) * 
                        SIN(lieuArrivee.lat * PI() / 180) + 
                        COS(:lat * PI() / 180) * 
                        COS(lieuArrivee.lat * PI() / 180) * 
                        COS((:lon – lieuArrivee.lon) * PI() / 180)
                        ) * 
                    180 / PI()
                ) 
                * 60 * 1.1515 AS `distance`,  '
            )
        ;

        $parameters['lat']  = $lat;
        $parameters['lng']  = $lng;

        $query->where('voyage.published = :published');
        $parameters['published']    = 1;


        if($locality != ''){
            $parameters     = $
            $query->orWhere('lieuArrivee.locality LIKE :locality');
            $parameters['locality'] = $locality;
        }

        if($country != ''){
            $query->orWhere('lieuArrivee.country LIKE :country');
            $parameters['country']  = $country;
        }



    }
}
