<?php

namespace AppBundle\Repository;

/**
 * EtapeLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeLieuRepository extends \Doctrine\ORM\EntityRepository
{
}
