<?php

namespace AppBundle\Repository;

/**
 * Etape_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etape_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
