<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use AppBundle\Entity\Voyage;
use AppBundle\Model\MainSearch;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param $entityAlias
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias)
    {

        $queryBuilder   = $this->createQueryBuilder($entityAlias)
            ->join('e.lieuArrivee','lieuArrivee')
                ->join($entityAlias.'.lieuDepart','lieuDepart')
                ->join($entityAlias.'.voyage','voyage')
                ->join('AppBundle:User', 'owner', 'WITH', 'voyage.owner=owner.id')
                ->leftJoin('AppBundle:Image', 'image', 'WITH', 'owner.photoProfile=image.id')
                ->addSelect('lieuArrivee')
                ->addSelect('lieuDepart')
                ->addSelect('voyage')
                ->addSelect('owner')
                ->addSelect('image')
            ;

        return $queryBuilder;
    }

    public function mainSearch(MainSearch $data){
        
        if($data->getLat() == null || $data->getLng() == null) return null;

       $query   = $this->createSearchQueryBuilder('etape')
           ->addSelect('lieuArrivee')
           ->addSelect('lieuDepart')
           ->addSelect('voyage')
           ->addSelect('owner')
           ->addSelect('image')
           ->addSelect(
               '
                    ST_Distance(
                            POINT(lieuArrivee.lat,lieuArrivee.lng),
                            POINT(:lat, :lng)
                    ) * 3.14/ 180 * 6371 as distance '
           );
        
        
    }


    /**
     * @param Voyage $voyage
     * @return array
     */
    public function getEtapesByVoyage(Voyage $voyage)
    {
        $query  = $this->createQueryBuilder('e')
            ->where('e.voyage_id = :id')
            ;
        $query->setParameter('id', $voyage->getId());

        return $query->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @return array
     */
    public function getEtapeByUser(User $user){
        $query  = $this->createQueryBuilder('e')
            ->select('e')
            ->join('AppBundle:Voyage','v','WITH','e.voyage=v.id')
            ->where('v.owner = :owner_id')
            ->setParameter('owner_id', $user->getId())
            ->orderBy('e.dateFinSejour','desc')
        ;

        return $query->getQuery()->getResult();
    }
}
