<?php

namespace AppBundle\Repository;
use AppBundle\Model\MainSearch;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @param $entityAlias
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias)
    {

        $queryBuilder   = $this->createQueryBuilder($entityAlias)
            ->join('e.lieuArrivee','lieuArrivee')
                ->join($entityAlias.'.lieuDepart','lieuDepart')
                ->join($entityAlias.'.voyage','voyage')
                ->join('AppBundle:User', 'owner', 'WITH', 'voyage.owner=owner.id')
                ->leftJoin('AppBundle:Image', 'image', 'WITH', 'owner.photoProfile=image.id')
                ->addSelect('lieuArrivee')
                ->addSelect('lieuDepart')
                ->addSelect('voyage')
                ->addSelect('owner')
                ->addSelect('image')
            ;

        return $queryBuilder;
    }

    public function mainSearch(MainSearch $data){
        
        if($data->getLat() == null || $data->getLng() == null) return null;

       $query   = $this->createSearchQueryBuilder('etape')
           ->addSelect('lieuArrivee')
           ->addSelect('lieuDepart')
           ->addSelect('voyage')
           ->addSelect('owner')
           ->addSelect('image')
           ->addSelect(
               '
                    ST_Distance(
                            POINT(lieuArrivee.lat,lieuArrivee.lng),
                            POINT(:lat, :lng)
                    ) * 3.14/ 180 * 6371 as distance '
           );
        
        
    }
}
