<?php

namespace AppBundle\Repository;

/**
 * HobbieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbieRepository extends \Doctrine\ORM\EntityRepository
{
}
