<?php

namespace AppBundle\Repository;

/**
 * LieuEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
