<?php

namespace AppBundle\Repository;

/**
 * LieuTagLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuTagLieuRepository extends \Doctrine\ORM\EntityRepository
{
}
