<?php

namespace AppBundle\Repository;

/**
 * niveau_confortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class niveau_confortRepository extends \Doctrine\ORM\EntityRepository
{
}
