<?php

namespace AppBundle\Repository;

/**
 * PhobbieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhobbieRepository extends \Doctrine\ORM\EntityRepository
{
}
