<?php

namespace AppBundle\Repository;

/**
 * TagLieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagLieuRepository extends \Doctrine\ORM\EntityRepository
{
}
