<?php

namespace AppBundle\Repository;

/**
 * UserActivitesSportivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivitesSportivesRepository extends \Doctrine\ORM\EntityRepository
{
}
