<?php

namespace AppBundle\Repository;

/**
 * UserHobbieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHobbieRepository extends \Doctrine\ORM\EntityRepository
{
}
