<?php

namespace AppBundle\Repository;

/**
 * UserLangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLangueRepository extends \Doctrine\ORM\EntityRepository
{
}
