<?php

namespace AppBundle\Repository;

/**
 * UserEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
