<?php

namespace AppBundle\Repository;

/**
 * UserCauseSocialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCauseSocialeRepository extends \Doctrine\ORM\EntityRepository
{
}
