<?php

namespace AppBundle\Repository;

/**
 * UserPhobbieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPhobbieRepository extends \Doctrine\ORM\EntityRepository
{
}
