assetic:
    bundles: ~
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
      cssrewrite: ~
      lessphp:
          file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
          apply_to: ".less$"
          formatter: "compressed"
          preserve_comments: false
      jsqueeze: ~
    assets:
      font_awesome_css:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/less/font-awesome.less"
          filters:
              - lessphp
              - cssrewrite
          output: "css/font-awesome.css"
      font_awesome_fonts_eot:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot"
          output: "fonts/fontawesome-webfont.eot"
      font_awesome_fonts_svg:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg"
          output: "fonts/fontawesome-webfont.svg"
      font_awesome_fonts_ttf:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf"
          output: "fonts/fontawesome-webfont.ttf"
      font_awesome_fonts_woff:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff"
          output: "fonts/fontawesome-webfont.woff"
      font_awesome_fonts_woff2:
          inputs:
              - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2"
          output: "fonts/fontawesome-webfont.woff2"
      jquery_js:
          inputs:
              - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"
          output: "js/jquery.min.js"
      jquery_ui_js:
          inputs:
              - "%kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.min.js"
          output: "js/jquery-ui.min.js"
      jquery_ui_css:
          inputs:
              - "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/jquery-ui.min.css"
          filters:
              - lessphp
              - cssrewrite
          output: "css/jquery-ui.css"
      images_jquery_ui1:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-bg_flat_0_aaaaaa_40x100.png"
          output: "images/ui-bg_flat_0_aaaaaa_40x100.png"
      images_jquery_ui2:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_444444_256x240.png"
          output: "images/ui-icons_444444_256x240.png"
      images_jquery_ui3:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_555555_256x240.png"
          output: "images/ui-icons_555555_256x240.png"
      images_jquery_ui4:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_777620_256x240.png"
          output: "images/ui-icons_777620_256x240.png"
      images_jquery_ui5:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_777777_256x240.png"
          output: "images/ui-icons_777777_256x240.png"
      images_jquery_ui6:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_cc0000_256x240.png"
          output: "images/ui-icons_cc0000_256x240.png"
      images_jquery_ui7:
          inputs: "%kernel.root_dir%/../vendor/components/jqueryui/themes/base/images/ui-icons_ffffff_256x240.png"
          output: "images/ui-icons_ffffff_256x240.png"
      bootstrap_css:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
              - "%kernel.root_dir%/../src/AppBundle/Resources/public/vendor/bootstrap-multiselect/dist/less/bootstrap-multiselect.less"
          filters:
              - lessphp
              - cssrewrite
          output: "css/bootstrap.css"
      bootstrap_js:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
              - "%kernel.root_dir%/../src/AppBundle/Resources/public/vendor/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"
          output: js/bootstrap.js
      fonts_glyphicons_eot:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
          output: "fonts/glyphicons-halflings-regular.eot"
      fonts_glyphicons_svg:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
          output: "fonts/glyphicons-halflings-regular.svg"
      fonts_glyphicons_ttf:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
          output: "fonts/glyphicons-halflings-regular.ttf"
      fonts_glyphicons_woff:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"
          output: "fonts/glyphicons-halflings-regular.woff"
      fonts_glyphicons_woff2:
          inputs:
              - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff2"
          output: "fonts/glyphicons-halflings-regular.woff2"
