app:
    resource: "@AppBundle/Resources/config/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

