security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    session_fixation_strategy: migrate
    role_hierarchy:
        ROLE_PRO: ROLE_USER
        ROLE_ADIM: ROLE_PRO
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:  homepage
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/voyage/, role: ROLE_USER }
        - { path: ^/myprofile/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }