# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        arguments: [%fos_user.model.user.class%,'@service_container']
        tags:
            - {name: form.type, alias: app_user_profile}
    app.form.voyage:
        class: AppBundle\Form\VoyageType
        arguments: ['@service_container']
        tags:
            - {name: form.type, alias: voyage_form}
    app.form.voyage2:
        class: AppBundle\Form\VoyagePart2Type
        arguments: ['@service_container']
        tags:
            - {name: form.type, alias: voyage_form2}
    app.form.search.voyage:
        class: AppBundle\Form\SearchVoyageCompleteType
        arguments: ['@service_container']
        tags:
            - {name: form.type, alias: search_voyage}

    trav.fileuploader:
        class: AppBundle\Service\FileUploader
    trav.form.methods:
        class: AppBundle\Service\FormServices
        arguments: ['@service_container']

    # Repositories
    trav.repository.address:
        class: AppBundle\Repository\AddressRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Address']

    trav.repository.userdata:
        class: AppBundle\Repository\UserDataRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:UserData']
    trav.repository.country:
        class: AppBundle\Repository\CountriesRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Countries']

    trav.repo.address.manipulator:
            class: AppBundle\RepositoryManipulat\AddressRepoManipulator
            arguments: ['@service_container']
    trav.repository.genre:
        class: AppBundle\Repository\GenreRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Genre']

