homepage:
    path: /{_locale}/home/
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'

trav_contact:
    path: /{_locale}/ourstory/contact/
    defaults:
        _controller: AppBundle:Default:contact
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_marketplace:
    path: /{_locale}/exclusivities/marketplace/
    defaults:
        _controller: AppBundle:Default:marketplace
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_bonplan:
    path: /{_locale}/exclusivities/tips/
    defaults:
        _controller: AppBundle:Default:bonplan
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_aboutus:
    path: /{_locale}/ourstory/aboutus/
    defaults:
        _controller: AppBundle:Default:aboutus
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_faq:
    path: /{_locale}/ourstory/faq/
    defaults:
        _controller: AppBundle:Default:faq
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_search_form:
    path: /{_locale}/search/
    defaults:
        _controller: AppBundle:Default:search
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_myprofile:
    path: /{_locale}/myprofile/
    defaults:
        _controller: AppBundle:Travelleurs:myprofile
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_showmyprofile:
    path: /{_locale}/showmyprofile/
    defaults:
        _controller: AppBundle:Travelleurs:showmyprofile
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_edit_address:
    path: /{_locale}/address/edit/{user}
    defaults:
        _controller: AppBundle:Default:editaddress
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
        user: '\d+'
trav_add_profile_image:
    path: /ajax/profile/image/send/{user}
    defaults:
        _controller: AppBundle:Default:addProfileImage
    requirements:
        user: '\d+'

trav_edit_voyage:
    path: /{_locale}/voyage/edit/{id}
    defaults:
        _controller: AppBundle:Voyage:edit
    requirements:
        id: '\d+'
        _locale: '%regex.local%'

trav_add_voyage:
    path: /{_locale}/voyage/add
    defaults:
        _controller: AppBundle:Voyage:add
    requirements:
        _locale: '%regex.local%'

trav_index_voyage:
    path: /{_locale}/voyage/list
    defaults:
        _controller: AppBundle:Voyage:index
root:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'