homepage:
    path: /{_locale}/home/
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'

trav_contact:
    path: /{_locale}/ourstory/contact/
    defaults:
        _controller: AppBundle:Default:contact
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_marketplace:
    path: /{_locale}/exclusivities/marketplace/
    defaults:
        _controller: AppBundle:Default:marketplace
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_bonplan:
    path: /{_locale}/exclusivities/tips/
    defaults:
        _controller: AppBundle:Default:bonplan
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_aboutus:
    path: /{_locale}/ourstory/aboutus/
    defaults:
        _controller: AppBundle:Default:aboutus
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_faq:
    path: /{_locale}/ourstory/faq/
    defaults:
        _controller: AppBundle:Default:faq
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_search_form:
    path: /{_locale}/search/
    defaults:
        _controller: AppBundle:Default:search
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_mypage:
    path: /{_locale}/mypage/
    defaults:
        _controller: AppBundle:Travelleurs:mypage
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
root:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'