homepage:
    path: /{_locale}/home/
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'

trav_contact:
    path: /{_locale}/ourstory/contact/
    defaults:
        _controller: AppBundle:Default:contact
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_marketplace:
    path: /{_locale}/exclusivities/marketplace/
    defaults:
        _controller: AppBundle:Default:marketplace
        _locale: "%locale%"
    requirements:
        _locale: '%regex.local%'
trav_bonplan:
    path: /{_locale}/exclusivities/tips/
    defaults:
        _controller: AppBundle:Default:bonplan
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_aboutus:
    path: /{_locale}/ourstory/aboutus/
    defaults:
        _controller: AppBundle:Default:aboutus
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_faq:
    path: /{_locale}/ourstory/faq/
    defaults:
        _controller: AppBundle:Default:faq
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_search_form:
    path: /{_locale}/voyage/search/{page}
    defaults:
        _controller: AppBundle:Voyage:search
        _locale: '%locale%'
        page: 1
    requirements:
        _locale: '%regex.local%'
        page: '\d+'
trav_myprofile:
    path: /{_locale}/myprofile/
    defaults:
        _controller: AppBundle:Travelleurs:myprofile
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_showmyprofile:
    path: /{_locale}/showmyprofile/
    defaults:
        _controller: AppBundle:Travelleurs:showmyprofile
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_edit_address:
    path: /{_locale}/address/edit/{user}
    defaults:
        _controller: AppBundle:Default:editaddress
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
        user: '\d+'
trav_add_profile_image:
    path: /{_locale}/travelleurs/add/profilephoto/{id}
    defaults:
        _controller: AppBundle:Image:imageprofile
        _locale: '%locale%'
    requirements:
        id: '\d+'
        _locale: '%regex.local%'

trav_edit_voyage:
    path: /{_locale}/voyage/edit/{id}
    defaults:
        _controller: AppBundle:Voyage:edit
    requirements:
        id: '\d+'
        _locale: '%regex.local%'

trav_add_voyage:
    path: /{_locale}/voyage/add
    defaults:
        _controller: AppBundle:Voyage:add
    requirements:
        _locale: '%regex.local%'
trav_remove_etape:
    path: /{_locale}/voyage/etape/remove/{id}
    defaults:
        _controller: AppBundle:Voyage:removeetape
    requirements:
        _locale: '%regex.local%'
        id: '\d+'
trav_remove_voyage:
    path: /{_locale}/voyage/remove/{id}
    defaults:
        _controller: AppBundle:Voyage:removevoyage
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
        id: '\d+'
trav_index_voyage:
    path: /{_locale}/voyage/list
    defaults:
        _controller: AppBundle:Voyage:index
        _locale: '%locale%'
trav_view_voyage:
    path: /{_locale}/voyage/view/{etape_id}
    defaults:
        _controller: AppBundle:Voyage:viewVoyage
        _locale: '%locale%'
    requirements:
        etape_id: '\d+'
        _locale: '%regex.local%'

trav_add_image:
    path: /{_locale}/myprofile/image/add
    defaults:
        _controller: AppBundle:Image:add
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
trav_register_inetape:
    path: /{_locale}/voyage/etape/register/{id}
    defaults:
        _controller: AppBundle:Voyage:register
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
        id: '\d+'
trav_unregister_inetape:
    path: /{_locale}/voyage/etape/unregister/{id}
    defaults:
        _controller: AppBundle:Voyage:unregister
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'
        id: '\d+'

root:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: '%locale%'
    requirements:
        _locale: '%regex.local%'