homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: en|fr

forbled_contact:
    path: /{_locale}/contact/
    defaults:
        _controller: AppBundle:Default:contact
        _locale: "%locale%"
