<?php

namespace AppBundle\Form;

use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class ProfileType extends BaseType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('firstname',TextType::class,[
            'label'=>'trav.form.firstname'
        ])
        ->add('name',TextType::class,[
            'label'=>'trav.form.lastname'
        ])
        ->add(
            'birthdate',
            BirthdayType::class,
            [
                'label'=>'trav.birthdate',
                'required'=>true
            ]
        )
        ->add('city',
            TextType::class,
            [
                'label' => 'trav.city'
            ])
        ->add('country',
            TextType::class,
            [
                'label' => 'trav.country',
                'attr' => ['class' => 'auto_country']
            ]
        )
        ->add('state',
            TextType::class,
            [
                'label' => 'trav.state'
            ]
        )
        ->add('latitude',HiddenType::class)
        ->add('longitude',HiddenType::class)
        ;
        
        
        
    }


}
